name: Update gist
on:
  push:
    branches: master
  schedule:
    - cron: "0 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update gist
        run: python chess_com_box.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 
          BILI_SESSDATA: ${{ secrets.BILI_SESSDATA }}
